# Generated by Django 2.2.5 on 2019-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.TextField(blank=True)),
                ('College', models.CharField(max_length=100)),
                ('Phone', models.PositiveIntegerField(blank=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Designations', models.CharField(default='', max_length=150)),
                ('Skill1', models.CharField(default='', max_length=100)),
                ('Skill2', models.CharField(default='', max_length=100)),
                ('Skill3', models.CharField(blank=True, default='', max_length=100)),
                ('Skill4', models.CharField(blank=True, default='', max_length=100)),
                ('GitHub', models.URLField(blank=True, default='', max_length=150)),
                ('Twitter', models.URLField(blank=True, default='', max_length=150)),
                ('LinkedIn', models.URLField(blank=True, default='', max_length=150)),
                ('Instagram', models.URLField(blank=True, default='', max_length=150)),
                ('Project1', models.CharField(default='', max_length=50)),
                ('Project1desc', models.CharField(default='', max_length=150)),
                ('Projecturl1', models.URLField(default='', max_length=150)),
                ('Project2', models.CharField(default='', max_length=50)),
                ('Project2desc', models.CharField(default='', max_length=150)),
                ('Projecturl2', models.URLField(default='', max_length=50)),
                ('Project3', models.CharField(default='', max_length=50)),
                ('Project3desc', models.CharField(default='', max_length=150)),
                ('Projecturl3', models.URLField(default='', max_length=50)),
                ('Project4', models.CharField(default='', max_length=50)),
                ('Project4desc', models.CharField(default='', max_length=150)),
                ('Projecturl4', models.URLField(default='', max_length=150)),
                ('image', models.FileField(default='Your Image', upload_to='upload')),
            ],
        ),
    ]
