# Generated by Django 2.2.5 on 2019-09-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20190905_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Designations',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='Project1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Project1desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='Project2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Project2desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='Project3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Project3desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='Project4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Project4desc',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='Projecturl1',
            field=models.URLField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Projecturl2',
            field=models.URLField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Projecturl3',
            field=models.URLField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='Projecturl4',
            field=models.URLField(blank=True, default='', max_length=50),
        ),
    ]
